if: branch = master
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libssl-dev
      - cmake
before_script:
  - export CC=gcc-8
  - export CXX=g++-8
  - cd Test
  - mv ../VoiceIt2.hpp .
  - mv ../json.hpp .
  - git submodule add https://github.com/whoshuu/cpr.git
  - git submodule update --init --recursive
  - cmake -D -CMAKE_CXX_COMPILER="/usr/bin/g++-8"
  - make CC=/usr/bin/gcc-8 CPP=/usr/bin/g++-8 CXX=/usr/bin/g++-8 LD=/usr/bin/g++-8
script: "./Test"
after_success:
  - ./update.sh
  - ./email.sh
notifications:
  slack:
    secure: UPnF2d7L0+hp/DcCO0X4qHkFG+rePXpJqScUj7XQ6Mt3o6ZbmotapkceZYjbuEaNWmv64jC0DdwoVSTzCl40DLcvgJY5R4qSCQSiqI6glX/efeQl7NZqrKULEsrqF2oNA4YnWxHBFL+eb2PLM7s0AsRJt+zU80zeLmT0VpOcZoebCVGqGYNFN0i+q2rl9yRzqWGirgAo1dcv9i/lBvgkLiiC7qNAm/WS1TGH0hlFNCShTgEmMdKKa1k9wu+KoO2cfFRDPqpJWEbMLNI0VF7qXfaXm8v6OaMUVvzizFyXkiE2xqNapotVYn2I+Ne5iuEGBd9GQAl0ncwmlXsdwMuTTbthfmaFRRfl92rrQP15b13h0MUJbSGr4dry7Aw5W9JFQfexhB+yr3UKNzCMoxgpfgy62dBxd+7szhDFeoyfG0J479Z9c7cmrX+M5rXoLR1eY3gM4TVQFpU0SByA3KfoNa62UiZXxuN/CM8RtUoxfc7mV7CDUm7sHSCzagBKkJ/BRB8W8Asnb000cVVgTwFVKsvWKGB++QNLG8BTXjZKbNU6qv3IwwYCjkF4AVbk7oSSOY5Q9aGW7/OdPKibV49DSGlzYp2G34y+097vQZU4wDRSGN6uZ2wLCSXhNIzKobk40je7PU5nprFLyqFFRA60H+VLzH6Y2s5VW6guulXx4iY=
  email:
    on_success: never
    on_failure: never
