matrix:
  include:
    - os: linux
        addons:
          apt:
            packages:
              - cmake
              - g++-8
              - openssl
before_script:
- git submodule add https://github.com/whoshuu/cpr.git
- git submodule update --init --recursive
- echo "set (CMAKE_CXX_STANDARD 11)\nproject (Tests)\ncmake_minimum_required(VERSION 2.8.12)\nadd_subdirectory(cpr)\ninclude_directories(${CPR_INCLUDE_DIRS})\nadd_executable(Test Test.cpp)\ntarget_link_libraries(Tests ${CPR_LIBRARIES})\n" > CMakeLists.txt
- cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl
- make
script: ./Test
